# Generated by Django 4.1.5 on 2023-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lastnews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnews',
            name='news_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
