# Generated by Django 4.1.5 on 2023-02-03 10:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_lastnews_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastnews',
            name='news_desc',
            field=tinymce.models.HTMLField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='news_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
