# Generated by Django 4.1.5 on 2023-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ipmodel_lastnews_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastnews',
            name='video',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
