# Generated by Django 4.1.5 on 2023-02-06 15:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_lastnews_news_image1_lastnews_news_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=70)),
                ('Requirement', tinymce.models.HTMLField()),
            ],
        ),
    ]
