# Generated by Django 4.1.5 on 2023-02-06 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastnews',
            name='post_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
