# Generated by Django 4.1.5 on 2023-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_category_lastnews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img2', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img3', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img4', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img5', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img6', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img7', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
                ('img8', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
