# Generated by Django 4.1.5 on 2023-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_chatbot_dataanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
