# Generated by Django 4.1.5 on 2023-02-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_personalcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='img1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news1/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='img2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news1/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='img3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news1/'),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='img4',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news1/'),
        ),
        migrations.AlterField(
            model_name='personalcv',
            name='cv',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news1/'),
        ),
    ]
